@hostname = http://localhost:3003/

POST {{hostname}}/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1oaGgiLCJpZCI6IjYzNDgxNGM4MGY1NjE4YTRkMzlmMGM4NiIsImlhdCI6MTY2NTczNzYwNH0.32D1jPaxuQ98o2n7h4vO7pVD1ltQk1mWFfnn4o6G4lE

{
    "title": "Ensimmäinen",
    "author": "tärkeä henkilö",
    "url": "jotain",
    "likes": 2,
    /*"userId": "634814c80f5618a4d39f0c86"*/
}
